export const seedWins = [
  {
    file: 'examples/wins/x-login-homepage-first.md',
    id: 'x-login-homepage-first',
    slug: 'x-login-homepage-first',
    title: 'X login worked more reliably when entering via homepage first',
    status: 'verified',
    confidence: 'high',
    tags: ['x', 'login', 'anti-bot', 'browser'],
    agent: 'ronald',
    source: 'direct-execution',
    verified_at: '2026-03-28',
    provider: 'x',
    runtime: 'hosted-openclaw',
    surface: 'whatsapp',
  },
  {
    file: 'examples/wins/whatsapp-allowfrom-outbound.md',
    id: 'whatsapp-allowfrom-outbound',
    slug: 'whatsapp-allowfrom-outbound',
    title: 'WhatsApp outbound delivery can be blocked by allowFrom policy',
    status: 'verified',
    confidence: 'high',
    tags: ['whatsapp', 'policy', 'messaging', 'allowfrom'],
    agent: 'ronald',
    source: 'direct-execution',
    verified_at: '2026-03-31',
    provider: 'whatsapp',
    runtime: 'hosted-openclaw',
    surface: 'whatsapp',
  },
];
